# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3aa0d3a0148ec8c026ad5090eef3f1006cf6abf22137fb82b805a98bb9394c64582f47fe652e3235ca5cb10dea2c4190102519e67daae742c0702c7f938c171

test:
  secret_key_base: ab48a971e196fccf3a009ee7d1d418dc3c421f8fde15c775b6bef007eedbc8d3e890c7557c2e358b909f03a06c14b7b65653a3bd6d2969216ef1d865d16c8721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
